import { beforeEach, describe, expect, it, vi } from "vitest";

const {
  mockGenerateTimestampedFilename,
  mockSaveTextFile,
  mockSaveBinaryFile,
} = vi.hoisted(() => ({
  mockGenerateTimestampedFilename: vi.fn(),
  mockSaveTextFile: vi.fn(),
  mockSaveBinaryFile: vi.fn(),
}));

vi.mock("../FileOperationsService", () => ({
  FileOperationsService: {
    FILTERS: {
      MARKDOWN: [{ name: "Markdown", extensions: ["md"] }],
      PDF: [{ name: "PDF", extensions: ["pdf"] }],
    },
    generateTimestampedFilename: mockGenerateTimestampedFilename,
    saveTextFile: mockSaveTextFile,
    saveBinaryFile: mockSaveBinaryFile,
  },
}));

import { MessageExportService } from "../MessageExportService";

describe("MessageExportService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("exports markdown with default sanitized prefix", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.md");
    mockSaveTextFile.mockResolvedValueOnce({
      success: true,
      filename: "chat-message.md",
    });

    const result = await MessageExportService.exportMessageText({
      format: "markdown",
      content: "# hello",
      sessionId: "abcdef1234",
      messageId: "m-12345678",
    });

    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith(
      "chat-message-abcdef12-m-123456",
      "md",
    );
    expect(mockSaveTextFile).toHaveBeenCalledWith(
      "# hello",
      [{ name: "Markdown", extensions: ["md"] }],
      "chat-message.md",
    );
    expect(result).toEqual({ success: true, filename: "chat-message.md" });
  });

  it("returns markdown save errors", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.md");
    mockSaveTextFile.mockResolvedValueOnce({
      success: false,
      error: "cancelled",
    });

    const result = await MessageExportService.exportMessageText({
      format: "markdown",
      content: "text",
      filenamePrefix: "custom-prefix",
    });

    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith(
      "custom-prefix",
      "md",
    );
    expect(result).toEqual({ success: false, error: "cancelled" });
  });

  it("exports pdf using generated bytes", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    const pdfBytes = new Uint8Array([1, 2, 3]);
    const generatePdfSpy = vi
      .spyOn(MessageExportService as any, "generatePdfFromText")
      .mockResolvedValueOnce(pdfBytes);
    mockSaveBinaryFile.mockResolvedValueOnce({
      success: true,
      filename: "chat-message.pdf",
    });

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "render me",
      filenamePrefix: "custom-pdf",
    });

    expect(generatePdfSpy).toHaveBeenCalledWith("render me");
    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith(
      "custom-pdf",
      "pdf",
    );
    expect(mockSaveBinaryFile).toHaveBeenCalledWith(
      pdfBytes,
      [{ name: "PDF", extensions: ["pdf"] }],
      "chat-message.pdf",
    );
    expect(result).toEqual({ success: true, filename: "chat-message.pdf" });
  });

  it("returns pdf export error when generation fails", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    vi.spyOn(MessageExportService as any, "generatePdfFromText").mockRejectedValueOnce(
      new Error("pdf failed"),
    );

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "render me",
    });

    expect(mockSaveBinaryFile).not.toHaveBeenCalled();
    expect(result).toEqual({ success: false, error: "pdf failed" });
  });
});
